name: SnazyParties
version: 1.0
main: land.face.SnazzyPartiesPlugin
author: Lozke
description: JUST USE IT
api-version: 1.14

commands:
  party:
    usage: /<command>
    aliases: p
    permission: party.use
    description: JUST DO IT